Projects/Core+React/Northwind.Web/Areas/Admin/Controllers/HomeSectionController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Northwind.Core.Entities;
using Northwind.Core.Entities.HomePage;
using Northwind.Core.Interfaces;
using Northwind.Core.Interfaces.HomePage;
using Northwind.Core.Specifications;
using Northwind.Web.Infrastructure.Helpers;
using Northwind.Web.Infrastructure.Models;
using Northwind.Web.Models.ViewModels.Article;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;

namespace Northwind.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class HomeSectionController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly IMapper _mapper;
        private readonly IFileService _fileService;
        private readonly IConfiguration _configuration;
        private readonly IUserService _userService;
        string documentRoot;

        public HomeSectionController(IArticleService articleService, IMapper mapper, IFileService fileService, IConfiguration configuration, IUserService userService)
        {
            _articleService = articleService;
            _mapper = mapper;
            _fileService = fileService;
            _configuration = configuration;
            _userService = userService;
            documentRoot = configuration.GetSection("Document").GetValue<string>("DocumentRoot");

        }

        public ActionResult Index()
        {
            ViewBag.ArticleTypes = GetComboData();
            return View();
        }

        public ActionResult AddArticle()
        {
            ViewBag.ArticleTypes = GetComboData();
            return View(new ArticleViewModel());
        }

        public async System.Threading.Tasks.Task<IActionResult> GetArticle(string searchValue, int pageSize, int skip, int take, string sortField, string dir, int showDraft = 0, string additionalFilter ="")
        {
            try
            {
                var searchspec = new SearchSpec();
                searchspec.Dir = dir;
                searchspec.SearchText = searchValue;
                searchspec.PageSize = pageSize;
                searchspec.Skip = skip;
                searchspec.Take = take;
                searchspec.SortField = sortField;
                int articalTypeNumber = 0;
                bool showDraftedArticle = false;
                if(!string.IsNullOrEmpty(additionalFilter))
                {
                    var articalType = _articleService.GetArticleTypeByName(additionalFilter);
                    if (articalType.Result != null)
                    {
                        articalTypeNumber = articalType.Result.ArticleTypeId;
                    }
                }
                if (showDraft > 0)
                    showDraftedArticle = true;

                var articleData = await _articleService.GetArticles(articalTypeNumber, searchspec, showDraftedArticle);

                var result = articleData.Select(x => new
                {
                    Id = x.ArticleId,
                    Title = x.Title,
                    ShowInArchive = (x.ShowInArchive == true ? "Yes" : "No"),
                    IslocalMedia = (x.IsLocalMedia == true ? "Yes" : "No"),
                    Excerpt = x.Excerpt,
                    ArticleTypeName = x.ArticleTypeName,
                    IsFeatured = (x.IsFeatured == true ? "Yes" : "No"),
                    Body = x.Body,
                    MediaCaption = x.MediaCaption,
                    Status = x.Status.ToString(),
                    UpdatedOn = x.UpdatedOn.ToString("MM/dd/yyyy"),
                    CreatedOn = x.CreatedOn?.ToString("MM/dd/yyyy"),
                    CreatedByName = x.CreatedByName,
                    UpdatedByName =x.UpdatedByName

                }).ToList();

                var totalCount = await _articleService.TotalArticleRecord(searchValue);
                return Ok(new { result, count = totalCount });

            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
                return BadRequestFormatter.BadRequest(this, e);
            }
        }

        [HttpPost]
        [IgnoreAntiforgeryToken]
        public ActionResult AddUpdate(ArticleViewModel model, IFormFile file, string Submit)
        {
            if (ModelState.IsValid)
            {
                Article article = _mapper.Map<Article>(model);
                if (Request.Form.Files.Count > 0)
                {
                    var fullPhysicalFilePath = string.Concat(documentRoot, "\\Article\\Images");
                    var uniqueFileName =
                         _fileService.SaveFile(fullPhysicalFilePath, file);

                    var relativeFilePath = Path.Combine("Article\\Images", uniqueFileName);
                    article.PrimaryMediaPath = relativeFilePath;
                }
                article.CreatedOn = model.Date;
                article.CreatedBy = UserHelper.CurrentUserGuid(HttpContext);
                article.UpdatedOn = CurrentDateTimeHelper.GetCurrentDateTime();
                article.UpdatedBy = UserHelper.CurrentUserGuid(HttpContext);
                if (Submit == "Publish")
                {
                    article.Status = ArticleStatus.Published;
                }
                else
                {
                    article.Status = ArticleStatus.Draft;
                }
                article.IsDeleted = false;
                if (model.Action == "Edit")
                {
                    if (Submit == "Update and Publish")
                    {
                        article.Status = ArticleStatus.Published;
                    }
                    _articleService.Update(article);
                }
                else
                {
                    _articleService.Add(article);
                }
                return RedirectToAction("Index");
            }
            ViewBag.ArticleTypes = GetComboData();
            return View( "AddArticle", new ArticleViewModel());
            
        }

        private List<SelectListItem> GetComboData()
        {
            var comboListData = new List<SelectListItem>();
            var comboData = _articleService.GetArticleTypes().Result;
            if (comboData != null && comboData.Count() > 0)
            {
                comboListData = comboData.Select(data => new SelectListItem { Text = data.Name, Value = data.ArticleTypeId.ToString() }).ToList();
            }

            return comboListData;

        }

        public async System.Threading.Tasks.Task<IActionResult> EditArticle(int Id)
        {
          var data = await _articleService.GetArticle(Id);
            ViewBag.ArticleTypes = GetComboData();
            ArticleViewModel articleViewModel = _mapper.Map<ArticleViewModel>(data);
            articleViewModel.Date = data.CreatedOn;
            articleViewModel.Action = "Edit";
            articleViewModel.Body = HttpUtility.HtmlDecode(articleViewModel.Body);
            return  PartialView(articleViewModel);
        }

        public async System.Threading.Tasks.Task<IActionResult> DeleteArticle(int Id)
        {
            Article article = new Article();
            article.ArticleId = Id;
            await _articleService.Delete(article);
            return RedirectToAction("Index");
        }
        [HttpPost]
        [IgnoreAntiforgeryToken]
        public IActionResult DeleteMultiple([FromBody] int[] ids)
        {
            _articleService.DeleteMultiple(ids);
            return Ok(new { status = ResponseStatus.success.ToString(), message = "Successfully Deleted !!" });
        }

        public async System.Threading.Tasks.Task<IActionResult> GetArticlesForHomePage(ArticleTypes articleTypes)
        {
            try
            {
                var articleData = await _articleService.GetArticlesForHomePage(articleTypes);
                return Ok(articleData);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
                return BadRequestFormatter.BadRequest(this, e);
            }
        }



    }
}

Projects/Core+React/Northwind.Web/Areas/Admin/Views/HomeSection/AddArticle.cshtml
@model Northwind.Web.Models.ViewModels.Article.ArticleViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section breadcrumb
    {
    <li class="breadcrumb-item"><a href="/Admin/Homesection">List of Articles</a></li>
    <li class="breadcrumb-item"><a href="#">Add Article</a></li>
}

<div>
    <partial name="_FormModelArticle.cshtml" />
</div>

@section Scripts {
    <script>
        $("#ArticleDate").kendoDatePicker();
        var editor = null;
        (function () {
            editor = window.richEditor.loadRichEditor('richtexteditor', '');

        })()

    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.js"></script>
}

Projects/Core+React/Northwind.Web/Areas/Admin/Views/HomeSection/EditArticle.cshtml
@using System.Web;
@model Northwind.Web.Models.ViewModels.Article.ArticleViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Article : Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section breadcrumb
    {
    <li class="breadcrumb-item"><a href="/Admin/Homesection">List of Articles</a></li>
    <li class="breadcrumb-item"><a href="#">Add Article</a></li>
}

<div>
    <partial name="_FormModelArticle.cshtml" />
</div>

@section Scripts {
    <script>
        $("#ArticleDate").kendoDatePicker();
        var editor = null;
        (function () {
            editor = window.richEditor.loadRichEditor('richtexteditor', '@Html.Raw(Model.Body)');

        })()

    </script>
}

Projects/Core+React/Northwind.Web/Areas/Admin/Views/HomeSection/Index.cshtml
@model Northwind.Web.Models.ViewModels.Article.ArticleViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .farclause_grid .btn-link {
        color: #00649B;
    }

        .farclause_grid .btn-link:hover {
            text-decoration: underline;
        }
</style>
@section breadcrumb
    {
    <li class="breadcrumb-item"><a href="/Admin/Settings">Settings</a></li>
    <li class="breadcrumb-item"><a href="#">Home Section</a></li>
}

<div id="articleGrid"></div>
<div id="dialog">
    <div class="content"></div>
</div>

@section Scripts {

    <script type="text/javascript">
        (function ()
        {
            window.article.articleList('Article List', '@User.Claims.Where(c=>c.Type.ToString() == "fullName").ToList()[0].Value');
        })()
    </script>
}

Projects/Core+React/Northwind.Web/Areas/Admin/Views/HomeSection/_FormModelArticle.cshtml
@model Northwind.Web.Models.ViewModels.Article.ArticleViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<style>
    .k-editor-textarea {
        margin-top: 0px!important;
        margin-bottom: 0px!important;
        height: 309px!important;
    }
  
</style>

<div class="">
    <div class="row">
        <div class="col">
            <h3 class="text-primary mb-0">What You Need to Know / Values Corner / More to Know</h3>
        </div>
        <div class="col-12">
            <p>News Posts</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <form asp-action="AddUpdate" asp-controller="HomeSection"  enctype="multipart/form-data" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row">
                    <div class="col-md-4 form-group">
                        <label asp-for="Date">Date</label>
                        @Html.TextBoxFor(x => x.Date, new { id = "ArticleDate", placeholder ="MM/dd/yyyy",
                        @class="form-control"})
                        @Html.ValidationMessageFor(x => x.Date)
                    </div>
                    <div class="col-md-4 form-group">
                        <label for="">Front Page Section</label>

                        <Select asp-for="ArticletypeId" asp-items="ViewBag.ArticleTypes" class="form-control">
                            <option value="">Please Select Article Type</option>

                        </Select>
                        <span asp-validation-for="ArticletypeId" class="text-danger"></span>
                    </div>
                </div>
                <div class="row align-items-center">
                    <div class="col-md-4 form-group">
                        <label for="">Front Page Image</label>
                        <input type="file" name="file" class="form-control">
                    </div>
                    <div class="col-md-6 form-group form-inline">
                        <div class="form-check mr-4 mt-1 mb-1">
                            <input class="k-checkbox" asp-for="ShowInArchive" type="checkbox" id="inlineFormCheck">
                            <label class="k-checkbox-label" for="inlineFormCheck">
                                Show in See Archive View
                            </label>
                            <span asp-validation-for="ShowInArchive" class="text-danger"></span>
                        </div>
                        <div class="form-check mt-1 mb-1">
                            <input class="k-checkbox" type="checkbox" asp-for="IsFeatured" id="inlineFormCheck1" >
                            <label class="k-checkbox-label" for="inlineFormCheck1">
                                Is Featured
                            </label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" type="text" class="form-control">
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="col-12 form-group">
                        <label for="">Front Page Excerpt</label>
                        <textarea asp-for="Excerpt" class="form-control"></textarea>
                        <span asp-validation-for="Excerpt" class="text-danger"></span>
                    </div>
                    @*<div class="col-md-4 form-group">
            <label for="">1st Image/Video</label>
            <input type="file" class="form-control">
        </div>
        <div class="col-12 form-group">
            <label for="Image/Video Caption"></label>
            <input type="text" class="form-control">
        </div>*@
                    @*<div class="col-12 form-group">
            <a href="" class="btn btn-primary">Add Image</a>
        </div>*@
                    <div class="col-12 form-group">
                        <label for="">Body of Article</label>
                        <div id="richtexteditor" class="default-upload"></div>
                    </div>
                    <input type="hidden" asp-for="ArticleId" />
                    <input type="hidden" asp-for="Action" />
                    @if (Model.Action == "Edit")
                    {
                        <div class="col-12 text-right">
                            <input type="submit" class="btn btn-dark mx-2" name="Submit" value="Update and Save as Draft" />
                            <input type="submit" class="btn btn-primary" name="Submit" value="Update and Publish" />
                        </div>
                    }
                    else
                    {
                        <div class="col-12 text-right">
                            <input type="submit" class="btn btn-dark mx-2" name="Submit" value="Save as Draft" />
                            <input type="submit" class="btn btn-primary" name="Submit" value="Publish" />
                        </div>
                    }
                </div>
            </form>
        </div>
        @*<div class="col-md-6">
            <div class="post">
                <div class="post-title">
                    PREVIEW POST - Preview template (3 views - slider / news article page / archive
                </div>
                <div class="post-preview">
                    <div class="post-preview-img">
                        <img src="/img/HooverDam.png" class="img-fluid" alt="">
                        <div class="post-preview-img-caption">helo</div>
                    </div>
                    <div class="post-preview-title">
                        Webmail Access for Office 365
                    </div>
                    <div class="post-preview-date">
                        11/11/2019
                    </div>
                    <div class="post-preview-detail">
                        North Wind Webmail access for Office 365 users is accessible at the
                        URL https://outlook.office.com. We have experienced problems with users accessing the old
                        Webmail link, so please access. We have experienced problems with users accessing the old
                        Webmail link.<br><br>

                        North Wind Webmail access for Office 365 users is accessible at the URL
                        https://outlook.office.com. We have experienced problems with users accessing the old Webmail
                        link, so please access your webmail directly at this.<br><br>

                        North Wind Webmail access for Office 365 users is accessible at the URL
                        https://outlook.office.com. We have experienced problems with users accessing the old Webmail
                        link, so please access your webmail directly at this URL.<br><br>
                    </div>
                    <div class="post-category">Category: <i>News</i></div>
                </div>
            </div>
        </div>*@
    </div>

</div>